### ISSUE TITLE
Error in attachment's

### ISSUE THREAD

**Issue by alcomic** [LeMarck/smtp#1]
Письма приходят с пустыми файлами.
All attachment's are empty.

**Comment by LeMarck** [comment]
@majackov, всё передаётся. Программа **не отслеживает** размер загружаемого файла. У письма есть **ограничение на размер вложений (примерно 25 МБ)**.
![](https://s32.postimg.org/e9wdkayud/image.jpg)

**Comment by alcomic** [comment]
Простой текстовик с хелоу ворлд не отправил, странно
